version: '3'

services:
  neo4j:
    image: alexpappasc/neo4j-apoc-algo:3.5.11
    ports:
    - "7474:7474"
    - "7687:7687"
    restart: always
    environment:
    - NEO4J_apoc_export_file_enabled=true
    - NEO4J_apoc_import_file_enabled=true
    - NEO4J_apoc_import_file_use__neo4j__config=true
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*, algo.*
    - NEO4J_AUTH=none
